### ISSUE TITLE
Errors in Angular2 (Angular cli) application after updating from 1.6.1 to version 1.7.0

### ISSUE THREAD

**Issue by wadenweh** [kutyel/linq.ts#41]
Hi, 
I am using linqts within an angular-cli project.
There is a problem with linqts, since I updated from 1.6.1 to 1.7.0. 
I am not sure, if it is a webpack or angular-cli problem - or just my fault. 
Maybe someone here can help.

system: windows 7
node:  v7.3.0
npm: 4.0.2

My project uses angular-cli version 1.0.0-beta.24.
When updating linqts to version 1.7.0, the angular 2 app throws this error:
```
zone.js:682Uncaught Error: Cannot find module "."
    at webpackMissingModule (linq.js:8) [<root>]
    at List.List.elements (linq.js:8) [<root>]
    at Object.<anonymous> (linq.js:13) [<root>]
    at __webpack_require__ (bootstrap c8b9130…:52) [<root>]
    at Object.481 (main.ts:12) [<root>]
    at __webpack_require__ (bootstrap c8b9130…:52) [<root>]
    at Object.482 (app.component.ts:24) [<root>]
    at __webpack_require__ (bootstrap c8b9130…:52) [<root>]
    at Object.372 (src async:7) [<root>]
    at __webpack_require__ (bootstrap c8b9130…:52) [<root>]
    at Object.694 (main.bundle.js:223) [<root>]
    at __webpack_require__ (bootstrap c8b9130…:52) [<root>]
    at webpackJsonpCallback (bootstrap c8b9130…:23) [<root>]
    at :4200/main.bundle.js:1:1 [<root>]
ZoneAwareError @ zone.js:682
webpackMissingModule @ linq.js:8
List.List.elements @ linq.js:8
(anonymous) @ linq.js:13
__webpack_require__ @ bootstrap c8b9130…:52
481 @ main.ts:12
__webpack_require__ @ bootstrap c8b9130…:52
482 @ app.component.ts:24
__webpack_require__ @ bootstrap c8b9130…:52
372 @ src async:7
__webpack_require__ @ bootstrap c8b9130…:52
694 @ main.bundle.js:223
__webpack_require__ @ bootstrap c8b9130…:52
webpackJsonpCallback @ bootstrap c8b9130…:23
(anonymous) @ main.bundle.js:1
```
To reproduce the Problem create a dummy project with:
```
  npm install -g webpack
  npm install -g webpack-dev-server
  npm install -g angular-cli
  ng new linqtstest
  cd linqtstest
  npm install linqts@latest -D
```
Replace the file linqtstest\src\app\app.component.ts with some linqts :
```
  import { Component } from '@angular/core';
  import { List, Enumerable } from 'linqts';

  @Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css']
  })
  export class AppComponent {
    name: string;
    private linqs: string[];
    constructor() {
      this.name = 'LinqTs + Angular2'
      this.linqs = Enumerable
        .Range(1, 5)
        .Select(i => 'LinqTs ' + i)
        .ToArray();
    }

    foo(l: string): void {
      console.log(l);
      alert(l)
    }
  }
```
Replace the file linqtstest\src\app\app.component.html with the following
```
  <div>
    <h2>Hello {{name}}</h2>
      <button *ngFor="let l of linqs" (click)="foo(l)" md-fab>
          <span>{{l}}</span>
      </button>
  </div>
```
Run the dummy project with:
```
  ng serve
```
The app should now run on http://localhost:4200 and You should see the described error.
The same app with linqts version 1.6.1 runs without any errors.

**Comment by kutyel** [comment]
Please try upgrading to v1.7.1 and it should be fixed :wink:

**Comment by wadenweh** [comment]
Hi,  thank you for the fast response!

I updated linqts to 1.7.1. but the same error still appears.

**Comment by kutyel** [comment]
Hi! Can you try the solution mentioned at https://github.com/kutyel/linq.ts/pull/43#issuecomment-272123019? Thanks in advance! 😉

**Comment by zskovacs** [comment]
I could reproduce your problem. It looks like WebPack cannot load linq.ts if it is compiled as UMD module. If I recompile it to commonjs, then it works fine. But I'm not sure this is a linq.ts problem. I tried it with SystemJS and it could handle it even if I used it as UMD.

**Comment by kutyel** [comment]
@kentcdodds Hi Kent! Sorry for mentioning you but I know you have dealt with this problem before, is there any way from my library that I can support both webpack/SystemJS and the UMD modules that I already have or it is a matter of how people use my library? 😟  This also happens in #40.

**Comment by kentcdodds** [comment]
Hey @kutyel, I generally distribute a UMD version as well as a CommonJS version of my modules. Watch [this](https://egghead.io/lessons/javascript-add-a-browser-build-to-an-npm-module) for more info. One important bit that's not noted in the video is that your `package.json` `main` is set to the CommonJS version. Also, in my video I'm using babel to generate the CommonJS version of my module, but you could use webpack to do this as well (if you need any loaders to run as part of your build for example).

Good luck!

**Comment by wadenweh** [comment]
Hi, @kutyel, I installed linqts 1.7.2. now I have another error. I do not know if it has anything to do with linqts, because the version 1.6.1 is not avalable anymore. 
With 1.7.2 The error looks like this:
``` 
linq.js:8
	Uncaught ZoneAwareErrorcode: "MODULE_NOT_FOUND"
	message: "Cannot find module ".""
	name: "Error"originalStack: 
	"Error: Cannot find module "."
		at ZoneAwareError (http://localhost:4200/vendor.bundle.js:87029:33)
		at webpackMissingModule (http://localhost:4200/vendor.bundle.js:81195:69)
		at List.List.elements (http://localhost:4200/vendor.bundle.js:81195:147)
		at Object.<anonymous> (http://localhost:4200/vendor.bundle.js:81200:3)
		at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)
		at Object.482 (http://localhost:4200/main.bundle.js:45:65)
		at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)
		at Object.483 (http://localhost:4200/main.bundle.js:93:73)
		at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)
		at Object.372 (http://localhost:4200/main.bundle.js:26:74)
		at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)
		at Object.699 (http://localhost:4200/main.bundle.js:237:18)
		at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)
		at webpackJsonpCallback (http://localhost:4200/inline.bundle.js:24:23)
		at http://localhost:4200/main.bundle.js:1:1"stack: "Error: Cannot find module "."
		at webpackMissingModule (http://localhost:4200/vendor.bundle.js:81195:69) [<root>]
		at List.List.elements (http://localhost:4200/vendor.bundle.js:81195:147) [<root>]
		at Object.<anonymous> (http://localhost:4200/vendor.bundle.js:81200:3) [<root>]
		at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30) [<root>]
		at Object.482 (http://localhost:4200/main.bundle.js:45:65) [<root>]
		at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30) [<root>]
		at Object.483 (http://localhost:4200/main.bundle.js:93:73) [<root>]
		at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30) [<root>]
		at Object.372 (http://localhost:4200/main.bundle.js:26:74) [<root>]
		at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30) [<root>]
		at Object.699 (http://localhost:4200/main.bundle.js:237:18) [<root>]
		at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30) [<root>]
		at webpackJsonpCallback (http://localhost:4200/inline.bundle.js:24:23) [<root>]
		at http://localhost:4200/main.bundle.js:1:1 [<root>]"
			toString: ...
		at webpackMissingModule (http://localhost:4200/vendor.bundle.js:81195:69) [<root>]
		at List.List.elements (http://localhost:4200/vendor.bundle.js:81195:147) [<root>]
		at Object.<anonymous> (http://localhost:4200/vendor.bundle.js:81200:3) [<root>]
		at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30) [<root>]
		at Object.482 (http://localhost:4200/main.bundle.js:45:65) [<root>]
		at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30) [<root>]
		at Object.483 (http://localhost:4200/main.bundle.js:93:73) [<root>]
		at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30) [<root>]
		at Object.372 (http://localhost:4200/main.bundle.js:26:74) [<root>]
		at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30) [<root>]
		at Object.699 (http://localhost:4200/main.bundle.js:237:18) [<root>]
		at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30) [<root>]
		at webpackJsonpCallback (http://localhost:4200/inline.bundle.js:24:23) [<root>]
		at http://localhost:4200/main.bundle.js:1:1 [<root>]"__proto__: ...
```
I try to friggle an CommonJs Verison of linqts. I am not an expert, but I will try and maybe it will help/work.

**Comment by wadenweh** [comment]
Hi @zskovacs. 
I can confirm, that changing the module output to es6 or commonjs solves the problem.
I changed .tsconfig to:
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es3",
        "outDir": "./dist",
        "declaration": true
    },
    "files": [
        "linq.ts"
    ],
    "exclude": [
        "node_modules"
    ]
}
```
and ran ```tsc```.
After replacing  ```node_modules/linqts/dist/linq.js``` with its commonjs version, and rebuilding, the errors are gone.

Thank You for the solution!

**Comment by kutyel** [comment]
Ok, it seems to me that is the same error that in #40 then, I am closing this in favor of it to keep track of the issue in just one place, thank you everyone! 😉
